version: 2

# Configuration File – Golangci-lint https://golangci-lint.run/docs/configuration/file/

# Linters – Golangci-lint https://golangci-lint.run/docs/linters/#Default
linters:
  # Default set of linters.
  # The value can be:
  #   - `standard`: enables linters tagged "Default".
  #   - `all`: enables all linters by default.
  #   - `none`: disables all linters by default.
  #   - `fast`: enables linters tagged "Fast".
  # Default: standard
  default: standard
  enable:
    # “Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.”
    # - errcheck
    # “Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes.”
    # - govet
    # “Detects when assignments to existing variables are not used.”
    # - ineffassign
    # “It's the set of rules from staticcheck.”
    # - staticcheck
    # “Checks Go code for unused constants, variables, functions and types.”
    # - unused
    #
    # Above are tagged "Default" and the below ones are not.
    #
    # “Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.”
    - revive
    # “Check exhaustiveness of enum switch statements.”
    - exhaustive
  settings:
    staticcheck:
      # checks:
      #   - "all"
      # Disable staticcheck's dot-imports check (ST1001).
      # - "-ST1001"
      dot-import-whitelist:
        - "github.com/knaka/go-utils"
    revive:
      rules:
      - name: dot-imports
        # Already checked with staticcheck's one.
        disabled: true
        # disabled: false
        # arguments:
        #   allowedPackages:
        #     - fmt
