#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_9d58e3d-false}" && return 0; sourced_9d58e3d=true

if test $# = 0
then
  set -- tasks
else
  task="$1"
  shift
  set -- run "$task" -- "$@"
  # set -- run "$task" "$@"
fi
sh mise "$@"
