#!/usr/bin/env sh
set -- __MISE_TASKS_TASKS_EXPAND_SH "$@"; eval "shift; \${$1-false} || ! $1=true" && return # shpp:source_guard

#MISE description="Generate Mise TOML tasks to call shell functions defined in monolithic shell files."

test "${_APPDIR+set}" = set || { cd "${0%[/\\]*}" 2>/dev/null || cd .; _APPDIR="$PWD"; cd "$OLDPWD" || exit; } 

# Parse shell task files and extract task/subcmd information with their metadata.
# Outputs lines in format: "<type> <name> <func_name> <basename> <body>"
extract_task_info() {
  test $# = 0 && return 0
  local script_path="$_APPDIR"/.assets/extract-task-info.awk
  if test -r "$script_path"
  then
    awk -f "$script_path" "$@"
  else
    # shellcheck disable=SC2016
    local scr='function reset_vars() {desc = "";delete mise_hdrs;mise_hdrs_count = 0;is_task = 0;task_name = "";}BEGIN {reset_vars();}/^#TASK($| +)/ {is_task = 1;if (/^.* name=/) {_ = $0;sub(/^.* name=/, "", _);sub(/ +.*$/, "", _);task_name = _;}if (/^.* desc=/) {_ = $0;sub(/^.* desc="/, "", _);sub(/".*$/, "", _);desc = _;}next;}/^#MISE / || /^# *\[MISE\] / {_ = $0;gsub(/^#MISE +/, "", _);gsub(/^# *\[MISE\] +/, "", _);mise_hdrs[mise_hdrs_count++] = _;next;}/^#/ {if (desc == "") {_ = $0;gsub(/^#+[ ]*/, "", _);desc = _;}next;}(is_task && /^[[:alnum:]_-].*\(\)/) || /^(task_|task-|subcmd_)[[:alnum:]_-].*\(\)/ {_ = $0;sub(/\(\).*$/, "", _);func_name = _;if (is_task) {type = "task";if (! task_name) {_ = func_name;gsub(/(__|--)/, ":", _);task_name = _;}} else {_ = func_name;sub(/[_-].*$/, "", _);type = _;_ = func_name;sub(/^[^_-]+[_-]/, "", _);gsub(/(__|--)/, ":", _);task_name = _;}_ = FILENAME;sub(/^.*\//, "", _);base = _;print type " " task_name " " func_name " " base " " desc;for (i = 0; i < mise_hdrs_count; i++) {type = "mise";print type " " task_name " " func_name " " base " " mise_hdrs[i];}reset_vars();next;}{reset_vars();}END {print "nop - - - -";}' #EMBED: ./.assets/extract-task-info.awk
    awk "$scr" "$@"
  fi
}

sh_task() { cat <<EOF
[tasks."$name"]
description='''$body'''
run='''
#!/usr/bin/env sh
# $TASKS_REL_DIR/$base:$func_name
saved_pwd_85053ae="\$PWD"
cd "\$MISE_PROJECT_ROOT"/"$TASKS_REL_DIR" || exit 1
set -- _SCRDIR "\$PWD" "\$@"
. ./"$base"
shift 2
cd "\$saved_pwd_85053ae" || exit 1
set -o nounset -o errexit
${func_name} "\$@"
'''
EOF
}

bash_task() { cat <<EOF
[tasks."$name"]
description='''$body'''
run='''
#!/usr/bin/env bash
# $TASKS_REL_DIR/$base:$func_name
pushd "\$MISE_PROJECT_ROOT"/"$TASKS_REL_DIR" >/dev/null || exit 1
. ./"$base"
popd >/dev/null || exit 1
set -o nounset -o errexit -o pipefail
${func_name} "\$@"
'''
EOF
}

# Read task info from stdin and generate TOML files for each source file.
# Groups tasks by their source basename and outputs _route-<basename>.toml files.
# Handles "task"/"subcmd" types by setting description and run script,
# and "mise" type by merging additional mise configuration headers.
generate_tasks() {
  local type name func_name base body
  while read -r type name func_name base body
  do
    case "$type" in
      (task|subcmd)
        echo
        case "$base" in
          (*.sh) sh_task;;
          (*.bash) bash_task;;
        esac
        ;;
      (mise)
        echo "$body"
        ;;
      (nop)
        ;;
      (*)
        exit 1
    esac
  done
}

is_mise_project_dir() {
  local dir=.
  test $# -gt 0 && dir="$1"
  # Configuration | mise-en-place https://mise.jdx.dev/configuration.html
     test -r "$dir"/mise.local.toml \
  || test -r "$dir"/mise.toml \
  || test -r "$dir"/mise/config.toml \
  || test -r "$dir"/.mise/config.toml \
  || test -r "$dir"/.config/mise.toml \
  || test -r "$dir"/.config/mise/config.toml \
  || test -d "$dir"/.config/mise/conf.d \
  #nop
}

expand() {
  cd "${INIT_CWD-}" || :
  cd "${MISE_ORIGINAL_CWD-}" || :
  cd "${INITIAL_DIR-}" || :
  while :
  do
    if is_mise_project_dir "$PWD"
    then
      break
    fi
    cd ..
    if test "$PWD" = "$OLDPWD"
    then
      echo Reached to the root. >&2
      return 1
    fi
  done
  mkdir -p ./.config/mise/conf.d
  {
    echo "# Code generated by tasks:expand task. DO NOT EDIT."
    for file in \
      "$PWD"/.config/mise/conf.d/tasks-*.sh \
      "$PWD"/.config/mise/conf.d/tasks-*.bash \
      "$PWD"/.config/mise/tasks-*.sh \
      "$PWD"/.config/mise/tasks-*.bash \
      "$PWD"/.mise/tasks-*.sh \
      "$PWD"/.mise/tasks-*.bash \
      "$PWD"/mise/tasks-*.sh \
      "$PWD"/mise/tasks-*.bash \
      "$PWD"/tasks-*.sh \
      "$PWD"/tasks-*.bash
    do
      test -r "$file" || continue
      local TASKS_DIR TASKS_REL_DIR
      TASKS_DIR="${file%/*}"
      TASKS_REL_DIR="${TASKS_DIR#"$PWD/"}"
      extract_task_info "$file" | generate_tasks
    done
  } >./.config/mise/conf.d/expanded-tasks.toml
}

if eval 'test "$0" = "${BASH_SOURCE-}"' || case "${0##*[/\\]}." in (expand.*) ;; (*) false;; esac # shpp:main_guard
then
  set -o nounset -o errexit
  expand "$@"
fi
